namespace:
  name: ingress-nginx

controller:
  image:
    repository: registry.k8s.io/ingress-nginx/controller
    tag: v1.8.2@sha256:74834d3d25b336b62cabeb8bf7f1d788706e2cf1cfd64022de4137ade8881ff2

admissionWebhook:
  image:
    repository: registry.k8s.io/ingress-nginx/kube-webhook-certgen
    tag: v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b

ingressClass:
  name: nginx

service:
  type: LoadBalancer
  controller:
    name: ingress-nginx-controller
    port:
      http: 80
      https: 443
  admissionController:
    name: ingress-nginx-controller-admission
    port: 443

resources:
  controller:
    requests:
      cpu: 100m
      memory: 90Mi

webhook:
  createJob:
    name: ingress-nginx-admission-create
  patchJob:
    name: ingress-nginx-admission-patch

