apiVersion: v2
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
type: application
maintainers:
  - name: Musa
    email: musa.raja@gmail.com
  - name: ehsan
    email: ehsanuol@gmail.com
name: kube-prometheus-stack
sources:
  - ./
#  - ../../kube-prometheus-main
version: 51.3.0
appVersion: v0.68.0
kubeVersion: ">=1.19.0-0"
#home: ../../kube-prometheus-main
home: ./
keywords:
  - operator
  - prometheus
  - kube-prometheus
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: ../
    - name: Upstream Project
      url: ../../kube-prometheus-main

dependencies:
  - name: crds
    version: "0.0.0"
    condition: crds.enabled
  - name: kube-state-metrics
    version: "5.14.*"
    directories: ./
    condition: kubeStateMetrics.enabled
  - name: prometheus-node-exporter
    version: "4.23.*"
    directories: ./
    condition: nodeExporter.enabled
  - name: grafana
    version: "6.60.*"
    directories: ./
    condition: grafana.enabled
  - name: prometheus-windows-exporter
    directories: ./
    version: "0.1.*"
    condition: windowsMonitoring.enabled